allow-lan: true
mode: Rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: '|RFC|HKCO'
  network: ws
  port: 8443
  server: hkco.cnabc.tk
  tls: tls
  type: vmess
  uuid: d5014a83-8aeb-4d8d-a85a-1643a4178469
  ws-opts:
    headers:
      Host: hkco.cnabc.tk
    path: /754d25
- alterId: 0
  cipher: auto
  name: '|Oracle|SG'
  network: ws
  port: 8443
  server: 104.18.38.155
  tls: tls
  type: vmess
  uuid: 404e0e68-258c-4a70-9987-203918ba9342
  ws-opts:
    headers:
      Host: sg.cnabc.tk
    path: /58a28b
- alterId: 0
  cipher: auto
  name: '|RFC|JPCO'
  network: ws
  port: 22
  server: jpco.cnabc.tk
  tls: tls
  type: vmess
  uuid: 33b2f0c6-c3d3-4ddd-a502-6220ab6d0720
  ws-opts:
    headers:
      Host: jpco.cnabc.tk
    path: /912241
- alterId: 0
  cipher: auto
  name: '|Alice|HK'
  network: ws
  port: 443
  server: 104.18.38.155
  tls: tls
  type: vmess
  uuid: cc30ce80-acbe-4603-bf29-d9f7f5acbf9d
  ws-opts:
    headers:
      Host: speedtest.cnabc.tk
    path: /c583a2
- alterId: 0
  cipher: auto
  name: '|RFC|Clawᵒᵘᵗ'
  network: ws
  port: 8443
  server: claw.cnabc.tk
  tls: tls
  type: vmess
  uuid: 756611d3-dc58-4322-9d0f-4fb97fa0384d
  ws-opts:
    headers:
      Host: fcc.cnabc.tk
    path: /eff842
- alterId: 0
  cipher: auto
  name: '|RFC|Claw'
  network: ws
  port: 443
  server: claw.cnabc.tk
  tls: tls
  type: vmess
  uuid: d8ba4f54-5db4-48d4-870f-a08783ff8a88
  ws-opts:
    headers:
      Host: claw.cnabc.tk
    path: /97fe54
- alterId: 0
  cipher: auto
  name: claw日本
  network: tcp
  port: 18124
  server: 240b:4009:25a:1801:0:c2fa:3f63:cfed
  tls: false
  type: vmess
  uuid: 3a2ef7fd-44da-4e29-8916-735418843419
proxy-groups: []
rules:
- DOMAIN-SUFFIX,google.com,DIRECT
socks-port: 7891
